feat: dns vpn for macos
PinkD/corplink-rs pull request #47
Opened 2024-10-12 10:31 UTC by fanwenlin

实现macOS上的DNS VPN，并支持通过配置文件开关

在vpn连接时同步修改dns配置，断开时自动恢复配置

实现上参考了[wg-quick](https://github.com/WireGuard/wireguard-tools/blob/master/src/wg-quick/darwin.bash)的启动命令，核心逻辑在`collect_new_service_dns`、`set_dns`、`del_dns`

2024-10-12 13:59 UTC, PinkD requested changes
从代码来看，实现上是要先把当前 dns 备份，然后再把服务器下发的配置应用下去。在退出时回滚配置。整体逻辑问题不大，但是函数和变量的命名需要再考虑一下。以及还需要考虑一个问题，如果程序 panic 了或者被 kill 了， dns 配置可能会没法正确回滚

2024-10-12 13:59 UTC, PinkD commented on src/main.rs
> +    if use_dns_vpn {
不太记得 cfg 的生效范围了，这里的宏能对下面的 if 生效吗？可以试试在 linux 或者 win 能不能编译成功

2024-10-12 13:59 UTC, PinkD commented on src/config.rs
> +    pub use_dns_vpn: Option<bool>,
`use_dns_vpn` ，使用 dns 的 vpn 。顺序有点问题，应该是 `use_vpn_dns` ？

2024-10-12 13:59 UTC, PinkD commented on src/dns.rs
> +    setted: bool,
`set` 本身就是过去式，没有 `setted` 一说

2024-10-12 13:59 UTC, PinkD commented on src/dns.rs
> +            let service = service.trim_start_matches('*').trim(); // Remove leading '*' and trim whitespace
注释放到上面，不要放到后面

2024-10-12 13:59 UTC, PinkD commented on src/dns.rs
> +            let dns_response = if dns_response.contains(" ") {
上面 trim 了，这里还会有 `" "` 吗

2024-10-12 13:59 UTC, PinkD commented on src/dns.rs
> +            let dns_response = if dns_response.contains(" ") {
哦，这里会输出 "`There aren't any DNS Servers set on xxx"` 。可以直接用 starts with 比较。现在的写法不够清晰

2024-10-12 13:59 UTC, PinkD commented on src/dns.rs
> +                .args(&dns_servers)
dns server 也要判空

2024-10-12 13:59 UTC, PinkD commented on src/dns.rs
> +            // 获取 DNS 服务器
代码里一般情况下不能有中文

2024-10-12 13:59 UTC, PinkD commented on src/dns.rs
> +    pub fn del_dns(&self) -> Result<(), Error> {
函数名没起好，下面 log 都打 `reset` 了，函数的作用也是回滚 dns 配置，不该叫 `del`

2024-10-12 14:01 UTC, PinkD commented on src/dns.rs
> +    pub fn del_dns(&self) -> Result<(), Error> {
其实是 `backup->set->restore` 的流程

2024-10-12 14:02 UTC, PinkD commented on src/dns.rs
> +    setted: bool,
从整个 pr 来看，这个字段没用，可以直接根据有没有备份来决定要不要还原，不需要单独的 flag

2024-10-12 16:17 UTC, fanwenlin commented on src/main.rs
> +    if use_dns_vpn {
查了下是函数/定义/代码块/模块级别的，这里确实有问题。修改后已验证可在linux编译

2024-10-12 16:20 UTC, fanwenlin commented on src/dns.rs
> +            let dns_response = if dns_response.contains(" ") {
这里是参考了wg-quick里的实现，没有用starts with是担心如果networksetup输出的文本变了，会影响到逻辑，所以感觉依赖文本匹配也不是一个很好的方案
<img width="837" alt="image" src="https://github.com/user-attachments/assets/999e94ca-e693-49f6-bf0a-61957caaed10">

2024-10-12 16:25 UTC, fanwenlin commented on src/dns.rs
> +    pub fn del_dns(&self) -> Result<(), Error> {
因为这三个函数实现很大程度上参考了[wg-quick](https://github.com/WireGuard/wireguard-tools/blob/master/src/wg-quick/darwin.bash)，所以命名也都保留了wg-quick里的命名。😂 这个还有必要再修改吗？

2024-10-12 16:44 UTC, fanwenlin commented
> 如果程序 panic 了或者被 kill 了， dns 配置可能会没法正确回滚

这个需要保障的话确实比较麻烦。不过我倾向于认为 大部分用户都不会有复杂的dns配置（默认路由器或者几个常用的dns地址），意外情况导致的dns配置丢失并不会有很大的损失

对于dns配置比较复杂的用户，可以默认关闭这项配置。如果也需要这个功能的话，我觉得更好的方案是支持连接时自定义调用外部程序，同时带上dns服务器，交给用户自己去配置？从而把风险外置

2024-10-12 17:00 UTC, PinkD requested changes

2024-10-12 17:00 UTC, PinkD commented on src/dns.rs
> +    pub fn del_dns(&self) -> Result<(), Error> {
如果你能用充分的理由说服我，我可以考虑保留 `add/del` 的命名方式

2024-10-13 07:07 UTC, fanwenlin commented on src/dns.rs
> +            let dns_response = if dns_response.contains(" ") {
已添加注释说明

2024-10-13 07:51 UTC, PinkD approved these changes

2024-10-13 07:51 UTC, merged